# Generated by Django 5.0.6 on 2024-06-26 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('CM', 'Commerce and Management'), ('EL', 'Electronics')], default='CS', max_length=2)),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6')], default='S4', max_length=2)),
                ('course', models.CharField(choices=[('BCA', 'Bachelor of Computer Application'), ('CS', 'B.Sc. Computer Science'), ('ELC', 'B.Sc. Electronics'), ('TAX', 'B.COM. Taxation'), ('FIN', 'B.COM. Finance'), ('BBA', ' Bachelor of Business Administration')], default='BCA', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('CM', 'Commerce and Management'), ('EL', 'Electronics')], default='CS', max_length=2)),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6')], default='S4', max_length=2)),
                ('course', models.CharField(choices=[('BCA', 'Bachelor of Computer Application'), ('CS', 'B.Sc. Computer Science'), ('ELC', 'B.Sc. Electronics'), ('TAX', 'B.COM. Taxation'), ('FIN', 'B.COM. Finance'), ('BBA', ' Bachelor of Business Administration')], default='BCA', max_length=3)),
                ('roll_number', models.CharField(max_length=2, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.stdprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
