# Generated by Django 5.0.6 on 2024-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdprofile',
            name='roll_number',
            field=models.CharField(max_length=2),
        ),
    ]
