# Generated by Django 5.0.6 on 2024-07-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_stdprofile_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unimarks', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.stdprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
