# Generated by Django 5.0.6 on 2024-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.CharField(choices=[('BCA', 'Bachelor of Computer Application'), ('CS', 'B.Sc. Computer Science'), ('ELC', 'B.Sc. Electronics'), ('TAX', 'B.COM. Taxation'), ('FIN', 'B.COM. Finance'), ('BBA', ' Bachelor of Business Administration')], max_length=3, unique=True),
        ),
    ]
