# Generated by Django 5.0.6 on 2024-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_classtimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimetable',
            name='semester',
            field=models.CharField(max_length=2),
        ),
    ]
