# Generated by Django 5.0.6 on 2024-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_examtimetable_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='semester',
            field=models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6')], max_length=2),
        ),
    ]
