# Generated by Django 5.0.6 on 2024-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_classtimetable_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='course',
            field=models.CharField(choices=[('BCA', 'Bachelor of Computer Application'), ('CS', 'B.Sc. Computer Science'), ('ELC', 'B.Sc. Electronics'), ('TAX', 'B.COM. Taxation'), ('FIN', 'B.COM. Finance'), ('BBA', ' Bachelor of Business Administration')], max_length=3),
        ),
    ]
